// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbchqxckyepyosxwxhui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhiY2hxeGNreWVweW9zeHd4aHVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MzQ1MDAsImV4cCI6MjA2OTMxMDUwMH0.EutCx7F3BIZh2xihy_1J15UZ-c44dA-hYDAX3W-tuOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});